{
  "type": "record",
  "name": "TripRecord",
  "namespace": "com.example.transport",
  "fields": [
    {
      "name": "gpsprovider",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "bookingid",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "market_regular",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "bookingid_date",
      "type": [
        "null",
        {
          "type": "long",
          "logicalType": "timestamp-millis"
        }
      ],
      "default": null
    },
    {
      "name": "vehicle_no",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "origin_location",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "destination_location",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "org_lat_lon",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "des_lat_lon",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "data_ping_time",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "planned_eta",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "current_location",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "destinationlocation",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "actual_eta",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "curr_lat",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "curr_lon",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "ontime",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "delay",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "originlocation_code",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "destinationlocation_code",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "trip_start_date",
      "type": [
        "null",
        {
          "type": "long",
          "logicalType": "timestamp-millis"
        }
      ],
      "default": null
    },
    {
      "name": "trip_end_date",
      "type": [
        "null",
        {
          "type": "long",
          "logicalType": "timestamp-millis"
        }
      ],
      "default": null
    },
    {
      "name": "transportation_distance_in_km",
      "type": [
        "null",
        "float"
      ],
      "default": null
    },
    {
      "name": "vehicletype",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "minimum_kms_to_be_covered_in_a_day",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "driver_name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "driver_mobileno",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "customerid",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "customernamecode",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "supplierid",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "suppliernamecode",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "material_shipped",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}