from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json


def connect_to_cassandra():
    try:
        # This secure connect bundle is autogenerated when you download your SCB, 
        # if yours is different update the file name below
        cloud_config= {
        'secure_connect_bundle': './../secure-connect-cassandra-demo.zip'
        }

        # This token JSON file is autogenerated when you download your token, 
        # if yours is different update the file name below
        with open("./../cassandra_demo-token.json") as f:
            secrets = json.load(f)

        CLIENT_ID = secrets["clientId"]
        CLIENT_SECRET = secrets["secret"]

        auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
        cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
        session = cluster.connect()

        print("✅ Connected to Cassandra")
        # Execute a simple query to test the connection
        row = session.execute("SELECT release_version FROM system.local").one()
        print(f"Cassandra release version: {row.release_version}")

        return session
    except Exception as e:
        print(f"Error connecting to Cassandra: {e}")
        return None
